(function(){var a,b,c,d,e,f,g,h,i,j;a=window.device,window.device={},c=window.document.documentElement,j=window.navigator.userAgent.toLowerCase(),device.ios=function(){return device.iphone()||device.ipod()||device.ipad()},device.iphone=function(){return d("iphone")},device.ipod=function(){return d("ipod")},device.ipad=function(){return d("ipad")},device.android=function(){return d("android")},device.androidPhone=function(){return device.android()&&d("mobile")},device.androidTablet=function(){return device.android()&&!d("mobile")},device.blackberry=function(){return d("blackberry")||d("bb10")||d("rim")},device.blackberryPhone=function(){return device.blackberry()&&!d("tablet")},device.blackberryTablet=function(){return device.blackberry()&&d("tablet")},device.windows=function(){return d("windows")},device.windowsPhone=function(){return device.windows()&&d("phone")},device.windowsTablet=function(){return device.windows()&&d("touch")&&!device.windowsPhone()},device.fxos=function(){return(d("(mobile;")||d("(tablet;"))&&d("; rv:")},device.fxosPhone=function(){return device.fxos()&&d("mobile")},device.fxosTablet=function(){return device.fxos()&&d("tablet")},device.meego=function(){return d("meego")},device.cordova=function(){return window.cordova&&"file:"===location.protocol},device.nodeWebkit=function(){return"object"==typeof window.process},device.mobile=function(){return device.androidPhone()||device.iphone()||device.ipod()||device.windowsPhone()||device.blackberryPhone()||device.fxosPhone()||device.meego()},device.tablet=function(){return device.ipad()||device.androidTablet()||device.blackberryTablet()||device.windowsTablet()||device.fxosTablet()},device.desktop=function(){return!device.tablet()&&!device.mobile()},device.portrait=function(){return window.innerHeight/window.innerWidth>1},device.landscape=function(){return window.innerHeight/window.innerWidth<1},device.noConflict=function(){return window.device=a,this},d=function(a){return-1!==j.indexOf(a)}}).call(this);(function(w,d){var $AA={};$AA.data=$AA.data||{};var AvanserOptions=w['AvanserOptions']||{};$AA.cookies={toObject:function(){var result={};if(d.cookie.length>0){var cookies=d.cookie.split('; ');for(var i=0;i<cookies.length;i++){var cur=cookies[i].split('=');result[cur[0]]=cur[1];}}
return result;},read:function(c_name,lowercase){if(d.cookie.length>0){c_start=d.cookie.indexOf(c_name+"=");if(c_start!=-1){c_start=c_start+c_name.length+1;c_end=d.cookie.indexOf(";",c_start);if(c_end==-1)c_end=d.cookie.length;var cookie_to_use=unescape(d.cookie.substring(c_start,c_end));if(lowercase){return cookie_to_use.toLowerCase();}
return cookie_to_use;}}
return'';},write:function(c_name,c_value){var exdate=new Date();exdate.setDate(exdate.getDate()+$AA.config.cookieExpireDays);c_value=escape(c_value)+(($AA.config.cookieExpireDays==null)?"":"; expires="+exdate.toUTCString())+";domain="+$AA.config.cookieDomain+";path=/";;d.cookie=c_name+"="+c_value;}};$AA.log=function(obj){if(console&&$AA.config.debug){console.log(obj);}}
$AA.utilities={proto:function(url){url=url.split(':');return url[0]||'';},host:function(url){url=url.split('/');return url[2]||'';},querystring:function(url){var qs=null,o={},qsv=null;if(url=="")return o;qs=url.toString();if(url.hash!="")
qs=qs.replace(url.hash,'');qs=qs.split('?');if(!qs||qs.length<2)return o;qs=qs[1];qs=qs.split('&');if(qs.length<=0)return o;for(var i=0;i<qs.length;i++){if(typeof qs[i]=='function')continue;qsv=qs[i].split('=');o[qsv[0]]=$AA.typeOf(qsv[1])=='undefined'?true:decodeURIComponent(qsv[1].replace('#',''));}
return o;},include:function(id,url){var s=d.createElement('SCRIPT');s.type='text/javascript';s.id=id;if(url.indexOf('http')==-1){url=w.location.protocol+'//'+url;}
s.src=$AA.utilities.cachebuster(url);var p=document.getElementsByTagName('script')[0];p.parentNode.insertBefore(s,p);},sendlog:function(url){if(!d.getElementById('AVANSERlog')){var i=d.createElement('IMG');i.id='AVANSERlog';if($AA.data.browser.indexOf('/(?i)MSIE [1-9]/')!=-1){i.style.cssText='visibility:none;display:none;position:absolute;top:-1;left:-1;z-index:0;';}else{i.style='visibility:none;display:none;position:absolute;top:-1;left:-1;z-index:0;';}
d.body.appendChild(i);}
if(url.indexOf('http')==-1){url=w.location.protocol+'//'+url;}
d.getElementById('AVANSERlog').src=$AA.utilities.cachebuster(url);},browser:function(){if($AA.typeOf($AA.data.browser)!='undefined')
return $AA.data.browser;var ua=navigator.userAgent,N=navigator.appName,tem,M=ua.match(/(opera|chrome|safari|firefox|msie|trident)\/?\s*([\d\.]+)/i)||[];M=M[2]?[M[1],M[2]]:[N,navigator.appVersion,'-?'];if(M&&(tem=ua.match(/version\/([\.\d]+)/i))!=null)M[2]=tem[1];$AA.data.browser=M.join(' ');},cachebuster:function(url){var cb=Math.round(new Date().getTime()/ 1000);return url.indexOf('?')!=-1?url+'&cb='+cb:url+'?cb='+cb;},toQuerystring:function(obj){var out=[];for(var k in obj){out.push(k+'='+encodeURIComponent(obj[k]));}
out=out.join('&');return out;},inArray:function(needle,haystack){var length=haystack.length;for(var i=0;i<length;i++){if(haystack[i]==needle)return true;}
return false;}};$AA.merge=function(src,target,overwrite){if($AA.typeOf(src)!='object')
return{};if($AA.typeOf(target)!='object')
target={};for(var k in src){if($AA.typeOf(src[k])=='object'){if(src[k]===target[k])continue;target[k]=$AA.merge(src[k],target[k]);}else if($AA.typeOf(src[k])!='undefined'&&($AA.typeOf(target[k])=='undefined'||overwrite)){target[k]=src[k];}
continue;}
return target;};$AA.typeOf=function(e){if(e===null)return'undefined';var out=(typeof e).toString().toLowerCase();if(out=='object'&&(typeof e.push).toString().toLowerCase()=='function'&&(typeof e.join).toString().toLowerCase()=='function'){out='array';}
return out;};var config={},q={};config.thisjs=d.getElementById('AVANSERjs');if(config.thisjs==null){$AA.log("AVANSER ERROR: inclusion not properly configured.");return;}
config.jsUrl=config.thisjs.src;params=$AA.utilities.querystring(config.jsUrl)
config.clientId=params.cId||AvanserOptions.clientId||'';config.trackingCode=params.tc||AvanserOptions.trackingCode||'';config.jsDomain=$AA.utilities.host(config.jsUrl);if($AA.typeOf(AvanserOptions.autostart)=='undefined'){if(params.autostart&&(params.autostart=='0'||params.autostart=='false')){AvanserOptions.autostart=false;}}
if($AA.typeOf(AvanserOptions.collector)=='undefined'&&params.collector&&params.collector!=''){AvanserOptions.collector=params.collector;}
if(config.clientId!=''&&config.trackingCode!=''){var tc=config.trackingCode;if($AA.typeOf(tc)=='array'){var minus_one=-1;if((minus_one=tc.indexOf('-1'))!=-1)
tc.splice(minus_one,1);if((minus_one=tc.indexOf(-1))!=-1)
tc.splice(minus_one,1);tc=tc.sort(function(a,b){return a-b});tc=tc.join('-');}
config.inclusion=w.location.protocol+'//'+config.jsDomain+'/static/'+config.clientId+'-'+tc+'.js?dn='+w.location.host;}else{config.clientDomain=w.location.host||d.location.host;config.inclusion=w.location.protocol+'//'+config.jsDomain+'/domains/'+config.clientDomain.toLowerCase()+'.js';}
w['AvanserOptions']=AvanserOptions;w['$AA']=$AA.merge(w['$AA']||{},$AA);$AA.utilities.browser();$AA.utilities.include('AVANSERcore',config.inclusion);})(window,document);